### ISSUE TITLE
Recent developments

### ISSUE THREAD

**Issue by logicReasoner** [dfsantamaria/DL4xD-Reasoner#3]
Hello,
has there been any recent progress on the following three fronts:
1) We plan to modify the set-theoretic fragment underpinning the reasoner so
as to include a restricted version of the operator of relational composition in
order to be able to reason with DLs admitting full existential and universal
quantification. 
2) We also intend to improve our reasoner so as to deal with the reasoning problem of ontology classification. We shall compare the resulting reasoner with
existing well-known reasoners such as Hermit [7] and Pellet [14], providing also
some benchmarking. 
3) In addition, we plan to allow data type reasoning by either
integrating existing solvers for the Satisfiability Modulo Theories (SMT) problem
or by designing ad hoc new solvers.

Thanks.

**Comment by dfsantamaria** [comment]
Good evening,
Step 2 has been completed. The results will appear on Fundamenta Informaticae. Concerning steps 1 and 3, they are in progress. Thank you.

**Comment by logicReasoner** [comment]
Good evening.

So when approximately should the code be updated on GitHub?

Best regards

**Comment by dfsantamaria** [comment]
Currently, we have no timeline for the next release.
